### ISSUE TITLE
Image crashes on Mac with M1

### ISSUE THREAD

**Issue by MDanialSaleem** [timescale/promscale_extension#22] opened 2021-08-03 08:40 UTC
Hey - The image does not work on Macs with the M1 chip.
1. It does not allow any connections
2. It crashes after a while with the following error message :  PANIC: stuck spinlock detected at LWLockWaitListLock, lwlock.c:833

A quick google search revealed [this PostGIS issue which appears to be similar](https://github.com/docker/for-mac/issues/5122)

**Comment by ramonguiu** [comment] 2021-08-10 12:32
Thanks for reporting the issue @MDanialSaleem and sorry for the delay.

What image are you referring to?

**Comment by MDanialSaleem** [comment] 2021-08-10 12:34
@ramonguiu thank you for the reply. 
I was referring to timescaledev/promscale-extension:latest-pg12

**Comment by ramonguiu** [comment] 2021-08-11 16:39
@MDanialSaleem I've tested and can reproduce your issue.
We are not providing an arm64 image and I suspect that's the main reason why it doesn't work. In theory amd64 images can work on Mac M1 (with poor performance) but ours may be calling some low level functions that cause it to crash.

I'll check with the team when we could provide a new image to test if this indeed the problem. Are you still trying to run in your M1 Mac or did you end up deploying somewhere else?

**Comment by MDanialSaleem** [comment] 2021-08-11 16:47
@ramonguiu thank you for checking.
Yea, so these images run under emulation and crash sometimes, really unpredictable which ones will run and which ones will crash.

So our deployment is on Intel machines and it works fine there. 
As far as dev is concerned, we are instead using timescale/timescaledb which we believe is identical except for optimizations and thus fine for dev use. Let me know if we are going wrong here.

Let me know if I can help with the multi-arch image release.

**Comment by ramonguiu** [comment] 2021-08-11 17:04
@MDanialSaleem thanks. timescaledev/promscale-extension builds on top of timescale/timescaledb by adding the promscale extension. [This](https://github.com/timescale/promscale_extension/blob/master/Dockerfile) is the Dockerfile.

Are you using Promscale or just TimescaleDB?

**Comment by MDanialSaleem** [comment] 2021-08-11 17:12
Based on my understanding from FAQ#1 [here](https://github.com/timescale/promscale/blob/master/docs/faq.md) 
1. promscale image in our compose file.
2. that image links to a timesacle/timescaledb image.


As far as I understand,  timescaledev/promscale-extension:latest-pg12 is a replacement for timescale/timescaledb to improve the performance of promscale with timescale db. Or am I wrong here?

**Comment by ramonguiu** [comment] 2021-08-12 10:29
That's correct. The promscale extension adds performance improvements but it's not strictly required.

**Comment by ramonguiu** [comment] 2021-12-10 22:38
#25 tracks publishing arm64 Docker images

**Comment by ramonguiu** [comment] 2021-12-10 23:42
Closing this one since we are tracking the work elsewhere.

**Closed by ramonguiu** 2021-12-10 23:42 UTC
Labels: Improvement
