### ISSUE TITLE
Installation issue in Ubuntu 20

### ISSUE THREAD

**Issue by asharabu** [timescale/promscale_extension#26] opened 2021-11-04 14:30 UTC
Hi,

I am trying to instal promscale_extenion in  Ubuntu 20 for postgres 13 and getting below error,

=========
root@test:/tmp/promscale_extension# make install
Makefile:58: warning: overriding recipe for target 'clean'
/usr/lib/postgresql/13/lib/pgxs/src/makefiles/pgxs.mk:355: warning: ignoring old recipe for target 'clean'
awk: warning: escape sequence `\.' treated as plain `.'
cargo build --release --features pg13
   Compiling pgx-pg-sys v0.1.19 (https://github.com/JLockerman/pgx.git?branch=guardless#c8248249)
error: failed to run custom build command for `pgx-pg-sys v0.1.19 (https://github.com/JLockerman/pgx.git?branch=guardless#c8248249)`

Caused by:
  process didn't exit successfully: `/tmp/promscale_extension/target/release/build/pgx-pg-sys-9f3dfc38e7b33114/build-script-build` (exit status: 1)
  --- stderr
  manifest_dir=/root/.cargo/git/checkouts/pgx-24f98968818058e4/c824824/pgx-pg-sys
  shim_dir=/root/.cargo/git/checkouts/pgx-24f98968818058e4/c824824/pgx-pg-sys/cshim
  Error: Custom { kind: NotFound, error: "/root/.pgx/config.toml not found.  Have you run `cargo pgx init` yet?" }
make: *** [Makefile:55: target/release/libpromscale_rs.a] Error 101

root@test:/tmp/promscale_extension# cargo pgx init --pg13=/usr/lib/postgresql/13/bin/pg_config
error: no such subcommand: `pgx`
        Did you mean `fix`?

=============

**Comment by JamesGuthrie** [comment] 2021-11-16 16:53
@asharabu did you install `cargo-pgx`? The instructions in the README are: `cargo install --git https://github.com/JLockerman/pgx.git --branch timescale cargo-pgx`

**Comment by ramonguiu** [comment] 2022-01-04 10:45
Closing since we can't reproduce. Reopen if the issue still persists.

**Closed by ramonguiu** 2022-01-04 10:45 UTC
Labels: Bug
